### ISSUE TITLE
Phase 2, part 1

### ISSUE THREAD

**Issue by ApertureTS** [SreeniASU/multimedia-information-systems#20]
I will complete the last part of part one. as I said earlier, I will be gone this weekend, and have limited internet access.  Let me know what else I can do.

**Comment by Perryo** [comment]
Hey guys, I got the bones of Part one redone. I have the functionality of storing the last few frames and doing calculations on them, however I need some clarification on the requirements as the output doesn't look quite right to me when we calculate the errors for the second frame instead of using the initial (for PC3).

**Comment by jakepruitt** [comment]
Hey @Perryo, didn't see this until now, we ended up doing similar work in #22

**Comment by Perryo** [comment]
Can you guys merge your part 1 changes into master?

**Comment by jakepruitt** [comment]
If you think the code is ready, I'm comfortable with you merging it.
